### ISSUE TITLE
tkn crash observed during `tkn pr logs -f` on windows 

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/cli#1132]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b3b92b2", GitCommit:"b3b92b2", GitTreeState:"clean", BuildDate:"2020-07-15T09:27:21Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+08c38ef", GitCommit:"08c38ef", GitTreeState:"clean", BuildDate:"2020-07-30T18:43:47Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  $ tkn version
  Client version: 0.11.0
  Pipeline version: v0.14.3
  Triggers version: v0.6.1
  ```

- Operating System:

  ```
  Windows
  ```

# Expected Behavior
`tkn` should not crash

# Actual Behavior
`tkn` got crashed during execution of `tkn pr logs -f`. This happened only once, I could not reproduce the issue

# Steps to Reproduce the Problem
Since it happened only once, there are no particular steps to reproduce the issue

# Additional Info
Command execution logs
```
C:\Users\Admin>tkn pr logs -f
E0818 11:01:59.502102    9264 runtime.go:78] Observed a panic: "send on closed channel" (send on closed channel)
goroutine 1317 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1652580, 0x1a76820)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xaa
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1652580, 0x1a76820)
        /usr/lib/golang/src/runtime/panic.go:679 +0x1c0
github.com/tektoncd/cli/pkg/pods.(*Pod).watcher.func2(0x1829040, 0xc00068c000, 0x1829040, 0xc000317800)
        /builddir/build/BUILD/tekton-client-0.11.0-3/pkg/pods/pod.go:106 +0x4f
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/client-go/tools/cache/controller.go:205
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0xc000764f00, 0x0, 0xc000bdfea0)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/client-go/tools/cache/shared_informer.go:656 +0x18f
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc000bdfdd8, 0xc000bdfee8, 0x44060f)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x58
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x80
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000bdff40)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x65
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000bdff40, 0xdf8475800, 0x0, 0x430501, 0xc0000704e0)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xff
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00088f780)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0xa2
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000106450, 0xc000c10000)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x60
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x69
panic: send on closed channel [recovered]
        panic: send on closed channel
goroutine 1317 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1652580, 0x1a76820)
        /usr/lib/golang/src/runtime/panic.go:679 +0x1c0
github.com/tektoncd/cli/pkg/pods.(*Pod).watcher.func2(0x1829040, 0xc00068c000, 0x1829040, 0xc000317800)
        /builddir/build/BUILD/tekton-client-0.11.0-3/pkg/pods/pod.go:106 +0x4f
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/client-go/tools/cache/controller.go:205
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0xc000764f00, 0x0, 0xc000bdfea0)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/client-go/tools/cache/shared_informer.go:656 +0x18f
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc00050bdd8, 0xc000bdfee8, 0x44060f)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x58
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x80
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000bdff40)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x65
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00050bf40, 0xdf8475800, 0x0, 0x430501, 0xc0000704e0)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xff
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00088f780)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0xa2
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000106450, 0xc000c10000)
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x60
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /builddir/build/BUILD/tekton-client-0.11.0-3/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x69
```

**Comment by tibcoplord** [comment]
I've seen the same on mac + docker for desktop -

```
E0106 08:40:54.706858   65299 runtime.go:78] Observed a panic: "send on closed channel" (send on closed channel)
goroutine 870 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x25b8720, 0x2a217b0)
	/workspace/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/runtime/runtime.go:48 +0x89
panic(0x25b8720, 0x2a217b0)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.com/tektoncd/cli/pkg/pods.(*Pod).watcher.func2(0x27f3f00, 0xc00017cc00, 0x27f3f00, 0xc0002c1000)
	/workspace/src/$(params.package)/pkg/pods/pod.go:107 +0x48
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/workspace/pkg/mod/k8s.io/client-go@v0.18.9/tools/cache/controller.go:225
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/workspace/pkg/mod/k8s.io/client-go@v0.18.9/tools/cache/shared_informer.go:742 +0x1c5
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000949f60)
	/workspace/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000563f60, 0x2a410c0, 0xc0004d7710, 0x257a101, 0xc000dd0b40)
	/workspace/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000949f60, 0x3b9aca00, 0x0, 0x1, 0xc000dd0b40)
	/workspace/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00047d400)
	/workspace/pkg/mod/k8s.io/client-go@v0.18.9/tools/cache/shared_informer.go:738 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000184760, 0xc000a2c010)
	/workspace/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:71 +0x65
panic: send on closed channel [recovered]
	panic: send on closed channel

goroutine 870 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x25b8720, 0x2a217b0)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.com/tektoncd/cli/pkg/pods.(*Pod).watcher.func2(0x27f3f00, 0xc00017cc00, 0x27f3f00, 0xc0002c1000)
	/workspace/src/$(params.package)/pkg/pods/pod.go:107 +0x48
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/workspace/pkg/mod/k8s.io/client-go@v0.18.9/tools/cache/controller.go:225
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/workspace/pkg/mod/k8s.io/client-go@v0.18.9/tools/cache/shared_informer.go:742 +0x1c5
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000949f60)
	/workspace/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000619f60, 0x2a410c0, 0xc0004d7710, 0x257a101, 0xc000dd0b40)
	/workspace/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000949f60, 0x3b9aca00, 0x0, 0x1, 0xc000dd0b40)
	/workspace/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00047d400)
	/workspace/pkg/mod/k8s.io/client-go@v0.18.9/tools/cache/shared_informer.go:738 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000184760, 0xc000a2c010)
	/workspace/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:71 +0x65
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T08:38:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

$ tkn version
Client version: 0.15.0
Pipeline version: v0.19.0
```
