### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tibcoplord** [tektoncd/cli#1350]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

 ```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
 ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

 ```
Client version: 0.17.1
Pipeline version: v0.23.0
 ```

- Operating System:

 ```
  MacOS Mig Sur
 ```

# Expected Behavior

`tkn pipelinerun logs --follow` completes successfully

# Actual Behavior

`tkn pipelinerun logs --follow` fails ( after some time running okay ) with

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x148ac51]

goroutine 157 [running]:
k8s.io/apimachinery/pkg/runtime.(*unstructuredConverter).ToUnstructured(0x35e0660, 0x0, 0x0, 0xc0003d6038, 0x0, 0xc0007f3e00)
	/private/tmp/tektoncd-cli-20210331-4989-pwx6d6/cli-0.17.1/vendor/k8s.io/apimachinery/pkg/runtime/converter.go:409 +0x171
github.com/tektoncd/cli/pkg/log.cast2taskrun(0x0, 0x0, 0x0, 0x0, 0x2)
	/private/tmp/tektoncd-cli-20210331-4989-pwx6d6/cli-0.17.1/pkg/log/task_reader.go:363 +0x68
github.com/tektoncd/cli/pkg/log.(*Reader).getTaskRunPodNames.func1(0xc000b1e5a0, 0xc000b1e600, 0x29d3d88, 0xc000b4fb00, 0xc000114288, 0xc000598160)
	/private/tmp/tektoncd-cli-20210331-4989-pwx6d6/cli-0.17.1/pkg/log/task_reader.go:258 +0x31c
created by github.com/tektoncd/cli/pkg/log.(*Reader).getTaskRunPodNames
	/private/tmp/tektoncd-cli-20210331-4989-pwx6d6/cli-0.17.1/pkg/log/task_reader.go:228 +0x2c5
```

# Steps to Reproduce the Problem

I expect this will be hard to replicate since it might depend on my tasks.  But I'm hoping the stack trace helps.

# Additional Info

**Comment by piyush-garg** [comment]
As this issue is 6 months old, having been not able to reproduce it and not any other case reported like this, I am closing this now. Feel free to open this if it happens again.
