### ISSUE TITLE
tkn pr delete fails if --keep-since and --ignore-running=false flag is used together when few pipelineRuns is in running state

### ISSUE THREAD

**Issue by divyansh42** [tektoncd/cli#1552]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**
   ```
  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

   ```
  Client version: 0.23.1
  Pipeline version: v0.34.1
  ```

- Operating System:

  ```
  Fedora 33
  ```

# Expected Behavior
When running
`tkn pr delete --keep-since=10 --ignore-running=false` should be able to delete pipelineRuns in running state also.

# Actual Behavior
`tkn pr delete --keep-since=10 --ignore-running=false` fails with error (When pipelineRuns in running state exists):
```
tkn pr delete --keep-since=10 --ignore-running=false
Are you sure you want to delete all PipelineRuns in namespace "default" except for ones created in last 10 minutes (y/n): y
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2278d7c]

goroutine 1 [running]:
github.com/tektoncd/cli/pkg/cmd/pipelinerun.keepPipelineRunsByAge(0x0, 0xa)
	/workspace/src/github.com/tektoncd/cli/pkg/cmd/pipelinerun/delete.go:291 +0x11c
github.com/tektoncd/cli/pkg/cmd/pipelinerun.allPipelineRunNames(0x57b54c, 0x0, 0xa, 0x0, {0x0, 0x1}, {0x2a218f7, 0x57ac7f})
	/workspace/src/github.com/tektoncd/cli/pkg/cmd/pipelinerun/delete.go:277 +0x10d
github.com/tektoncd/cli/pkg/cmd/pipelinerun.deletePipelineRuns(0xc000e9dd00, {0x2fbe508, 0xc000b32c00}, {0x47e8838, 0x0, 0x0}, 0xc0005f62a0)
	/workspace/src/github.com/tektoncd/cli/pkg/cmd/pipelinerun/delete.go:150 +0x61d
github.com/tektoncd/cli/pkg/cmd/pipelinerun.deleteCommand.func1(0xc00098ec80, {0xc0005d88c0, 0x0, 0x2})
	/workspace/src/github.com/tektoncd/cli/pkg/cmd/pipelinerun/delete.go:119 +0x2f0
github.com/spf13/cobra.(*Command).execute(0xc00098ec80, {0xc0005d88a0, 0x2, 0x2})
	/workspace/src/github.com/tektoncd/cli/vendor/github.com/spf13/cobra/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00099a000)
	/workspace/src/github.com/tektoncd/cli/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/src/github.com/tektoncd/cli/vendor/github.com/spf13/cobra/command.go:902
main.main()
	/workspace/src/github.com/tektoncd/cli/cmd/tkn/main.go:66 +0x365
```
# Steps to Reproduce the Problem

1. Create few pipelineRuns and make sure that few have completed it's execution and few are still in running state
2. Run `tkn pr delete --keep-since=10 --ignore-running=false` (Change values accordingly)

**Comment by piyush-garg** [comment]
@divyansh42 can we close this now ?

**Comment by divyansh42** [comment]
Yes
