### ISSUE TITLE
Panic on pipelinerun logs

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/cli#361]
# Expected Behavior
I can see logs of a pipelinerun

# Actual Behavior

I get a [panic](https://gist.github.com/afrittoli/d55fb5a2e9b65cf5bd922aa9d18f5fcb)

```
ERROR: logging before flag.Parse: E1015 15:44:43.665128   74185 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221084156-01f179d85dbc/pkg/util/runtime/runtime.go:76
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221084156-01f179d85dbc/pkg/util/runtime/runtime.go:65
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221084156-01f179d85dbc/pkg/util/runtime/runtime.go:51
/usr/local/Cellar/go/1.12.4/libexec/src/runtime/panic.go:522
/usr/local/Cellar/go/1.12.4/libexec/src/runtime/panic.go:82
/usr/local/Cellar/go/1.12.4/libexec/src/runtime/signal_unix.go:390
/go/src/github.com/tektoncd/cli/pkg/helper/pipelinerun/tracker.go:113
/go/src/github.com/tektoncd/cli/pkg/helper/pipelinerun/tracker.go:113
/go/src/github.com/tektoncd/cli/pkg/helper/pipelinerun/tracker.go:76
/go/pkg/mod/k8s.io/client-go@v0.0.0-20190226174127-78295b709ec6/tools/cache/controller.go:195
/go/pkg/mod/k8s.io/client-go@v0.0.0-20190226174127-78295b709ec6/tools/cache/shared_informer.go:554
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221084156-01f179d85dbc/pkg/util/wait/wait.go:203
/go/pkg/mod/k8s.io/client-go@v0.0.0-20190226174127-78295b709ec6/tools/cache/shared_informer.go:548
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221084156-01f179d85dbc/pkg/util/wait/wait.go:133
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221084156-01f179d85dbc/pkg/util/wait/wait.go:134
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221084156-01f179d85dbc/pkg/util/wait/wait.go:88
/go/pkg/mod/k8s.io/client-go@v0.0.0-20190226174127-78295b709ec6/tools/cache/shared_informer.go:546
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221084156-01f179d85dbc/pkg/util/wait/wait.go:71
/usr/local/Cellar/go/1.12.4/libexec/src/runtime/asm_amd64.s:1337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1ed28d0]

goroutine 28 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221084156-01f179d85dbc/pkg/util/runtime/runtime.go:58 +0x105
panic(0x207c540, 0x31121d0)
	/usr/local/Cellar/go/1.12.4/libexec/src/runtime/panic.go:522 +0x1b5
github.com/tektoncd/cli/pkg/helper/taskrun.HasScheduled(...)
	/go/src/github.com/tektoncd/cli/pkg/helper/taskrun/taskrun.go:54
Initial draft of the flip-coin pipeline
github.com/tektoncd/cli/pkg/helper/pipelinerun.(*Tracker).findNewTaskruns(0xc0000dc980, 0xc00021e6c0, 0x3148098, 0x0, 0x0, 0xc000001e00, 0xc000001e88, 0xc00013dbb8)
	/go/src/github.com/tektoncd/cli/pkg/helper/pipelinerun/tracker.go:113 +0x2a0
github.com/tektoncd/cli/pkg/helper/pipelinerun.(*Tracker).Monitor.func2(0x2209280, 0xc00021e6c0)
	/go/src/github.com/tektoncd/cli/pkg/helper/pipelinerun/tracker.go:76 +0x96
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190226174127-78295b709ec6/tools/cache/controller.go:195
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x102cffc, 0xc0004215e8, 0xc0004215e8)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190226174127-78295b709ec6/tools/cache/shared_informer.go:554 +0x26d
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0xc00002ce38, 0x102cb0f, 0xc000120170)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221084156-01f179d85dbc/pkg/util/wait/wait.go:203 +0xde
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190226174127-78295b709ec6/tools/cache/shared_informer.go:548 +0x89
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000421768)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221084156-01f179d85dbc/pkg/util/wait/wait.go:133 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00002cf68, 0xdf8475800, 0x0, 0x1, 0xc000672000)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221084156-01f179d85dbc/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221084156-01f179d85dbc/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0006de000)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190226174127-78295b709ec6/tools/cache/shared_informer.go:546 +0x9c
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000410060, 0xc00044a000)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221084156-01f179d85dbc/pkg/util/wait/wait.go:71 +0x4f
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221084156-01f179d85dbc/pkg/util/wait/wait.go:69 +0x62
```

# Steps to Reproduce the Problem

1. tkn pipeline start flip-coin-condition-demo --resource=coin=coin-bucket --resource=random=random-bucket
2. tkn pipelinerun logs flip-coin-condition-demo-run-8hzc6 -f -n default
3. Using pipeline and tasks defined: https://github.com/afrittoli/kubeflow-tekton-pipelines/tree/master/pipelines/condition

# Additional Info
Installed with:
```
$ git checkout v0.4.0
$ GO111MODULE=on go build ./cmd/tkn
$ mv tkn ~/bin/
```

On MacOS Mojava 10.14.6.
```
$ go version
go version go1.12.4 darwin/amd64
```

**Comment by hrishin** [comment]
Need to add `nil` [check](https://github.com/tektoncd/cli/blob/master/pkg/helper/taskrun/taskrun.go#L54)
